// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkWL1ZVBz1NMgvuFso4Gp6Qf6YnpgeJw',
    appId: '1:655399994430:web:2a922f2063da8a94ccfd6f',
    messagingSenderId: '655399994430',
    projectId: 'flutterfire-ui-codelab-19fdb',
    authDomain: 'flutterfire-ui-codelab-19fdb.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-19fdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdyWtN7fLHFlZXtbDXgsuGQiBCZ55hCc',
    appId: '1:655399994430:android:7604d27e8eb6e55fccfd6f',
    messagingSenderId: '655399994430',
    projectId: 'flutterfire-ui-codelab-19fdb',
    storageBucket: 'flutterfire-ui-codelab-19fdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wulW_kkG0j2HCB1YU-kcgk5cIEurZmE',
    appId: '1:655399994430:ios:0565abbe5b740b21ccfd6f',
    messagingSenderId: '655399994430',
    projectId: 'flutterfire-ui-codelab-19fdb',
    storageBucket: 'flutterfire-ui-codelab-19fdb.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_wulW_kkG0j2HCB1YU-kcgk5cIEurZmE',
    appId: '1:655399994430:ios:3d65f8cf53f827fcccfd6f',
    messagingSenderId: '655399994430',
    projectId: 'flutterfire-ui-codelab-19fdb',
    storageBucket: 'flutterfire-ui-codelab-19fdb.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
